application: changeme
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "5d"

handlers:
- url: /
  static_dir: static

- url: /.*
  static_files: 404.html
  upload: 404.html
